### ISSUE TITLE
slot number ahead of block number on kaustinen

### ISSUE THREAD

**Issue by gballet** [pk910/dora#39]
On kaustinen at least, it seems that the slot number is actually the block number (using a slot number of e.g. 74 yields the execution data for block number 74).

https://dora.kaustinen-testnet.ethpandaops.io/slot/74

But the block number itself is reported to be 116, which is wrong. If you look at the slots before and after, the block values are jumping widely, which has the result of the block numbers being AHEAD of the slot numbers. This should not happen on a testnet who merged at genesis.

**Comment by pk910** [comment]
Sorry for closing, clicked the wrong button 😉

**Comment by pk910** [comment]
Closing this, as the issue seems to be resolved :)
The URLs above do now show the correct block number.

I'm not sure why, I haven't done anything on dora side. 
Did you fix something on CL node side?

If not, it might have been an issue with the go-eth2-client library, which we "accidentally" fixed by rebasing the verkle  branch to latest master 😂.

**Comment by gballet** [comment]
That seems to have been fixed with the rebase, closing.
